# Generated by Django 4.2 on 2025-04-04 01:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservenue',
            unique_together={('user', 'venue')},
        ),
    ]
