# Generated by Django 4.2 on 2025-03-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='../guitar-logo-white_utocxc', upload_to='images/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
