# Generated by Django 4.2 on 2025-03-17 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
