# Generated by Django 4.2 on 2025-03-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="link_to_song",
            field=models.URLField(blank=True),
        ),
    ]
