# Generated by Django 4.2 on 2025-03-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_remove_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='net_votes',
            field=models.IntegerField(default=0),
        ),
    ]
