# Generated by Django 4.2 on 2025-04-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
